In [1]:
import numpy as np

In [2]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [5]:
B = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [7]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [8]:
x.T

array([1, 2, 3])

In [9]:
x.shape

(3,)

In [12]:
B = np.array([[2, -1],[8,0],[3,0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [13]:
np.dot(A,B)

array([[124,  -5],
       [ 36,   3]])